#ifndef ZPOGIF_ERROR_H
#define ZPOGIF_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
	ZPOGIF_NO_ERROR,
	ZPOGIF_IO_ERROR,
	ZPOGIF_OUT_OF_MEMORY,
	ZPOGIF_UNEXPECTED_BLOCK,
	ZPOGIF_UNEXPECTED_END_OF_BLOCK,
	ZPOGIF_UNEXPECTED_END_OF_FILE,
	ZPOGIF_INVALID_HEADER,
	ZPOGIF_INVALID_SEPARATOR,
	ZPOGIF_INVALID_EXTENSION_LENGTH,
	ZPOGIF_INVALID_EXTENSION_TERMINATOR,
	ZPOGIF_INVALID_EXTENSION_LABEL,
	ZPOGIF_NO_COLOR_TABLE,
	ZPOGIF_MALFORMED_IMAGE_DATA,
	ZPOGIF_ANIMATION_NOT_SUPPORTED,
	ZPOGIF_UNIDENTIFIED_ERROR
} zpogif_error;

#ifdef __cplusplus
}
#endif

#endif
